-- WUI Interactive — Supabase schema
-- Run this in the Supabase SQL Editor when you are ready to deploy.

create table if not exists public.app_state (
  id               int primary key default 1 check (id = 1),
  current_phase    text not null default 'lobby'
                   check (current_phase in ('lobby', 'game1', 'game2', 'game3', 'end')),
  active_question  int  not null default 1,
  results_open     boolean not null default false
);

insert into public.app_state (id, current_phase, active_question, results_open)
values (1, 'lobby', 1, false)
on conflict (id) do nothing;

alter table public.app_state add column if not exists results_open boolean not null default false;

create table if not exists public.game1_mapper (
  id              bigint generated by default as identity primary key,
  concept         text not null,
  assigned_phase  text not null check (assigned_phase in ('Before', 'During', 'After')),
  player_name     text not null default '',
  created_at      timestamptz not null default now()
);

alter table public.game1_mapper add column if not exists player_name text not null default '';

create table if not exists public.game2_trivia (
  id           bigint generated by default as identity primary key,
  question_id  int  not null,
  vote         text not null check (vote in ('Fact', 'Fiction')),
  player_name  text not null default '',
  created_at   timestamptz not null default now()
);

alter table public.game2_trivia add column if not exists player_name text not null default '';

create table if not exists public.game3_cloud (
  id           bigint generated by default as identity primary key,
  word         text not null,
  player_name  text not null default '',
  created_at   timestamptz not null default now()
);

alter table public.game3_cloud add column if not exists player_name text not null default '';

alter table public.app_state enable row level security;
alter table public.game1_mapper enable row level security;
alter table public.game2_trivia enable row level security;
alter table public.game3_cloud enable row level security;

drop policy if exists "anon all app_state" on public.app_state;
drop policy if exists "anon all game1_mapper" on public.game1_mapper;
drop policy if exists "anon all game2_trivia" on public.game2_trivia;
drop policy if exists "anon all game3_cloud" on public.game3_cloud;

create policy "anon all app_state" on public.app_state
  for all to anon, authenticated using (true) with check (true);
create policy "anon all game1_mapper" on public.game1_mapper
  for all to anon, authenticated using (true) with check (true);
create policy "anon all game2_trivia" on public.game2_trivia
  for all to anon, authenticated using (true) with check (true);
create policy "anon all game3_cloud" on public.game3_cloud
  for all to anon, authenticated using (true) with check (true);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.app_state, public.game1_mapper,
  public.game2_trivia, public.game3_cloud to anon, authenticated;
